name: Deploy To AWS
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: aws s3 sync dist s3://retail-kiosk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Alert
        if: ${{ failure() }}
        run: ./script/alert.sh
        env:
          ACTIONS_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          SOFTWARE_CHAT_WEBHOOK_URL: ${{ secrets.SOFTWARE_CHAT_WEBHOOK_URL }}
